### ISSUE TITLE
opnsense-patch support pull requests

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/update#30]
works exactly as a commit - would allow testing of PRs with many commits.

**Comment by fichtner** [comment]
I don't like it, because it provides anyone with the ability to open malicious PRs and force them on people in the default settings. It's even worse because PRs are volatile and their content can change and even consist of multiple patches we can't unroll again.

You can patch these already, but need to use -a and -r arguments to point to the correct account and repository.
