### ISSUE TITLE
Help wanted: insufficient disk-space for update

### ISSUE THREAD

**Issue by clystron** [opnsense/update#38]
I have an APU2 machine that failed to perform the update from 18.1 to 18.7 due to insufficient disk space. I did not install the machine myself but as far as I can tell it is a nano-image and the ~600MB of free disk space is not sufficient. There is more space available (its a 16GB SSD) but the original image only contains 2 ~2GB partitions and a 50MB partition. As far as I can tell only the very first 2GB partition is actually used, is there a way to grow the filesystem to use the whole disk? I have not found out what the second (and third) partition is for exactly, it seems the second 2GB partition is a second installation (backup?).

**Comment by fichtner** [comment]
Do you know what the initial image version of the nano installation was?

Can you post the output of "df -h"?

**Comment by clystron** [comment]
/dev/ufs/OPNsense0    1.8G    1.0G    622M    63%    /
devfs                 1.0K    1.0K      0B   100%    /dev
tmpfs                 2.9G    224M    2.6G     8%    /var
tmpfs                 2.6G    2.7M    2.6G     0%    /tmp
devfs                 1.0K    1.0K      0B   100%    /var/dhcpd/dev

That is after I deleted the opnsense-update folder in /root/var, before that it showed -132MB available and 108% usage on /dev/ufs/OPNSense0

I am not quite sure what the original image was, probably a 16.x

**Comment by fichtner** [comment]
It's what I feared... With the 16.x image we can't easily grow the disk anymore since it has a second partition that is in the way.

17.1 removed the second partition and made the image size a minimum of 3 GB and also added automatic FS grow on first boot. You're best off exporting your config.xml, dd'ing a new Nano to that SSD and reimport, or better yet use a serial image to do a "config import" + "guided install" to use the full ssd and retain all your settings / graphs.

**Comment by clystron** [comment]
I was afraid you were going to say that....
Would it be possible to create a new partition in the ~11GB free space and mount that on /root/var to get the update?
Re-Installation of that machine takes a little bit of planning because I need someone on site for that but I guess it really is the best option.

Thanks for your quick response!

**Comment by fichtner** [comment]
anything fiddling with the current disk layout should be considered higher risk. what could be tried is a staged update approach:

    # opnsense-update -ubkr 18.7

(reboot)

    # opnsense-update -upr 18.7

(reboot)

which splits the update sequence. but here also remote major upgrades on these components could be higher risk due to wear down of flash memory / FS errors / partial writes / power loss.

**Comment by clystron** [comment]
Thanks, will probably go the reinstall-route then

**Comment by AchimHentschel** [comment]
I had the same issue at the end of last week - not enough storage left in each of the 2 GB partitions on the device. I just tried the approach suggested by @fichtner (on Aug 6th). It failed: the server did not respond anymore after restarting. I installed a more recent image (18.1 instead of 18.7 where I head some issues using the serial connection to my APU) and after that did a restore of the whole config. And now everything is running like a charm again.
