### ISSUE TITLE
Update removing packages without replacement

### ISSUE THREAD

**Issue by andreas-p** [opnsense/update#51]
When updating from 19.1.6 to 19.1.7, the bind912 package was removed (probably because bind-tools-914 was to be installed), but bind914 wasn't installed so I was left with disfunctional local resolving. 

In general, the updater shouldn't remove a package without installing a replacement.

**Comment by fichtner** [comment]
You can report this to https://github.com/freebsd/pkg or https://bugs.freebsd.org/bugzilla/ or discuss this package split on the FreeBSD ports mailing list. It was a FreeBSD ports decision to break out bind-tools completely. There's nothing I can do here.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237551

All plugin dependencies have been correctly adjusted so you must have been assuming "bind912" is always there and use it manually.

https://github.com/opnsense/plugins/commit/942687d476

Looking at closer it's good that "pkg" uses consistency and force the stale package out rather than keeping the stale one and not updating correctly. If you run into these issues you can always lock the particular package from the GUI, but having said the previous it'll probably prevent you from updating correctly. It's an impossible choice to assume what the user wants so the system goes with a sane state.
